<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OzonAnalytics.Worker-c212e280-7927-4894-9ec7-55106e514007</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OzonAnalytics.Application\OzonAnalytics.Application.csproj" />
		<ProjectReference Include="..\OzonAnalytics.Infrastructure\OzonAnalytics.Infrastructure.csproj" />
	</ItemGroup>
</Project>
